version: '3'

services:
  redis:
    image: "redis:alpine"
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    stop_grace_period: "${DOCKER_STOP_GRACE_PERIOD:-3s}"

  celery:
    build: .
    command: celery -A main.app worker -l info
    volumes:
      - .:/code
    depends_on:
      - redis
      - celery-beat

  celery-beat:
    build: .
    command: celery -A main.app beat -l info
    volumes:
      - .:/code
    depends_on:
      - redis
